# Generated by Django 3.0 on 2019-12-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(help_text='UUID string', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True)),
                ('amount', models.IntegerField(blank=True)),
                ('currency', models.CharField(help_text='Currency', max_length=50)),
                ('employee_uuid', models.CharField(help_text='Employee uuid', max_length=50)),
                ('employee_first_name', models.CharField(help_text='Employee frist name', max_length=255)),
                ('employee_last_name', models.CharField(help_text='Employee last name', max_length=255)),
                ('status', models.CharField(choices=[('A', 'Approve'), ('D', 'Decline'), ('P', 'Pending')], default='P', max_length=1)),
            ],
        ),
    ]
