# Generated by Django 3.0 on 2019-12-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='currency',
            field=models.CharField(help_text='Currency', max_length=6),
        ),
    ]
